name: Publish to PyPI

on:
  # ① Push a tag like v0.1.3
  push:
    tags:
      - 'v*'
  # ② or press “Publish release” on GitHub
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build wheel & sdist
        run: |
          python -m pip install --upgrade build
          python -m build        # → ./dist/*.whl  and  ./dist/*.tar.gz

      - name: Upload to PyPI with Twine
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload --skip-existing dist/*
