# ─────────────────────────────────────────────────────────────
#  Publish SmurphCast to PyPI on every _GitHub Release_
#  (tag + release notes via the GitHub UI or `gh release …`)
#  Docs: https://docs.pypi.org/trusted-publishers/using-a-publisher/
# ─────────────────────────────────────────────────────────────
name: Upload Python Package

on:
  release:
    types: [published]          # fire ONLY when the release button is pressed

permissions:
  contents: read                # allow checkout
  id-token: write               # ***required for PyPI “trusted publishing”***

jobs:
# ───────────────────────────── 1. build the wheel / sdist ──
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build distributions
        run: |
          python -m pip install --upgrade build
          rm -rf dist/ build/
          python -m build              # creates wheel + sdist in ./dist

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

# ───────────────────────────── 2. upload to PyPI ────────────
  publish:
    runs-on: ubuntu-latest
    needs: build                  # wait for the build job
    environment:
      name: pypi                  # optional protected‑env name
      url: https://pypi.org/project/smurphcast
    permissions:
      id-token: write             # (repeat – required in _this_ job too)

    steps:
      - name: Download artefacts
        uses: pypa/gh-action-pypi-publish@release/v1

        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          packages-dir: dist/      # wheel + sdist from previous step
          skip-existing: true      # ignore if that exact version is already on PyPI
